### ISSUE TITLE
Allow targetRevision HEAD in the App filter

### ISSUE THREAD

**Issue by jay-jinjuwadia** [quizlet/argocd-diff-action#22]
Hi All,

Would it be possible to include `app.spec.source.targetRevision === 'HEAD'` as part of the app filter, since that is the revision ArgoCD defaults to when creating an application?
https://github.com/quizlet/argocd-diff-action/blob/4267297e35307515075a87fc65310bb6fbdba6df/src/main.ts#L105

**Comment by jay-jinjuwadia** [comment]
The maintainers don't seem to be viewing or actioning on issues, so I closed the ticket and changed my manifests to use the branch name instead of HEAD.

**Comment by Elyytscha** [comment]
you could reopen it and i would fix it in our fork, if they want they can merge it, if you want you could use our fork (until they merge or fix it).
